# Location to gene

## Preparation

In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

import json
import gffutils

In [3]:
project_path = Path().resolve().parent

## Load pangenome file

In [4]:
path_pangenome = project_path / "data" / "pangenome.tsv"

In [5]:
pangenome = pd.read_csv(path_pangenome, delimiter = "\t", header = None)
pangenome.columns = ["gene", "genome", "orthogroup"]
pangenome

                         gene           genome orthogroup
0             CP002034.1_1719  GCA_000143435.1  F00691_06
1           AEBA01000134.1_40  GCA_000179475.1  F00691_06
2           NBEP01000018.1_44  GCA_002079655.1  F00691_06
3           DONQ01000011.1_12  GCA_003513805.1  F00691_06
4          AFMN01000001.1_591  GCA_000215465.2  F00691_06
...                       ...              ...        ...
10096366  CABGJU010000006.1_8  GCA_902159415.1   F05974_2
10096367  CABGJU010000006.1_9  GCA_902159415.1   F10537_1
10096368  CABGJU010000007.1_1  GCA_902159415.1   F00820_1
10096369  CABGJU010000009.1_1  GCA_902159415.1   F21391_1
10096370  CABGJU010000010.1_1  GCA_902159415.1   F77991_1

[10096371 rows x 3 columns]

## Mobility frame

### Generate gene trees

In [6]:
pangenome = pangenome.iloc[0:120,:]
pangenome

                   gene           genome orthogroup
0       CP002034.1_1719  GCA_000143435.1  F00691_06
1     AEBA01000134.1_40  GCA_000179475.1  F00691_06
2     NBEP01000018.1_44  GCA_002079655.1  F00691_06
3     DONQ01000011.1_12  GCA_003513805.1  F00691_06
4    AFMN01000001.1_591  GCA_000215465.2  F00691_06
..                  ...              ...        ...
115  QFAS01000008.1_116  GCA_003129685.1   F00268_1
116   QSTB01000004.1_26  GCA_003438595.1   F00268_1
117   QSLH01000009.1_83  GCA_003470145.1   F00268_1
118   QRMK01000024.1_24  GCA_003472615.1   F00268_1
119       LT604075.1_72  GCA_900094615.1   F00268_1

[120 rows x 3 columns]

In [7]:
gff= "/Users/lorevansantvliet/Desktop/Thesis/Project/data/legen_v4_dereplicated_gffs/GCA_000006785.2.gff"

In [7]:
for orthogroup in pangenome.orthogroup.drop_duplicates():
    ortho=pangenome.loc[pangenome.orthogroup==orthogroup]
    for genome in ortho.genome.drop_duplicates():
        print(genome)
    print(ortho)

GCA_000143435.1
GCA_000179475.1
GCA_002079655.1
GCA_003513805.1
GCA_000215465.2
GCA_000217735.2
GCA_000260335.1
GCA_000529385.1
GCA_000758365.1
GCA_001011095.1
GCA_001063855.1
GCA_001067265.1
GCA_001435955.1
GCA_001723525.1
GCA_002079325.1
GCA_002079335.1
GCA_002079365.1
GCA_002079405.1
GCA_002079425.1
GCA_002079435.1
GCA_002079465.1
GCA_002079525.1
GCA_002079595.1
GCA_002079645.1
GCA_002079705.1
GCA_002079715.1
GCA_002079745.1
GCA_002079765.1
GCA_002079785.1
GCA_002079795.1
GCA_002079905.1
GCA_002079925.1
GCA_002135095.1
GCA_002159345.1
GCA_002160855.1
GCA_002161265.1
GCA_002162055.1
GCA_002250405.1
GCA_002289615.1
GCA_002289685.1
GCA_002289725.1
GCA_002289745.1
GCA_002289795.1
GCA_002289875.1
GCA_002553925.1
GCA_002554075.1
GCA_002738245.1
GCA_002848245.1
GCA_003129685.1
GCA_003316955.1
GCA_003438595.1
GCA_003470145.1
GCA_003472615.1
GCA_900094615.1
                  gene           genome orthogroup
0      CP002034.1_1719  GCA_000143435.1  F00691_06
1    AEBA01000134.1_40  GCA_000179475.1  F00691_06
2    NBEP01000018.1_44  GCA_002079655.1  F00691_06
3    DONQ01000011.1_12  GCA_003513805.1  F00691_06
4   AFMN01000001.1_591  GCA_000215465.2  F00691_06
5   AFOI01000002.1_167  GCA_000217735.2  F00691_06
6   AICL01000003.1_321  GCA_000260335.1  F00691_06
7   CBVR010000005.1_60  GCA_000529385.1  F00691_06
8      CP007646.1_1656  GCA_000758365.1  F00691_06
9      CP011403.1_1543  GCA_001011095.1  F00691_06
10    JVAF01000062.1_6  GCA_001063855.1  F00691_06
11   JUTI01000035.1_32  GCA_001067265.1  F00691_06
12   AYYT01000011.1_43  GCA_001435955.1  F00691_06
13      CP017107.1_540  GCA_001723525.1  F00691_06
14   NBEA01000023.1_11  GCA_002079325.1  F00691_06
15  NBDX01000006.1_140  GCA_002079335.1  F00691_06
16   NBDZ01000019.1_14  GCA_002079365.1  F00691_06
17   NBEE01000019.1_47  GCA_002079405.1  F00691_06
18  NBEF01000025.1_262  GCA_002079425.1  F00691_06
19   NBED01000031.1_25  GCA_002079435.1  F00691_06
20   NBEG01000023.1_67  GCA_002079465.1  F00691_06
21    NBEJ01000015.1_7  GCA_002079525.1  F00691_06
22   NBEN01000012.1_15  GCA_002079595.1  F00691_06
23   NBEQ01000027.1_26  GCA_002079645.1  F00691_06
24   NBES01000036.1_13  GCA_002079705.1  F00691_06
25   NBET01000025.1_14  GCA_002079715.1  F00691_06
26   NBEU01000019.1_14  GCA_002079745.1  F00691_06
27   NBEX01000059.1_49  GCA_002079765.1  F00691_06
28   NBEV01000040.1_52  GCA_002079785.1  F00691_06
29   NBEB01000074.1_15  GCA_002079795.1  F00691_06
30   MSCR01000028.1_49  GCA_002079905.1  F00691_06
31  NBDY01000012.1_247  GCA_002079925.1  F00691_06
32   LXZG01000117.1_12  GCA_002135095.1  F00691_06
33   NFHV01000005.1_50  GCA_002159345.1  F00691_06
34   NFLK01000001.1_87  GCA_002160855.1  F00691_06
35   NFHF01000008.1_72  GCA_002161265.1  F00691_06
36      CP020858.1_147  GCA_002162055.1  F00691_06
37   NDYW01000008.1_22  GCA_002250405.1  F00691_06
38   LXZS01000035.1_89  GCA_002289615.1  F00691_06
39   LXZL01000036.1_53  GCA_002289685.1  F00691_06
40    LXZJ01000081.1_7  GCA_002289725.1  F00691_06
41   LXZH01000021.1_25  GCA_002289745.1  F00691_06
42    LXZD01000184.1_2  GCA_002289795.1  F00691_06
43   LXZA01000077.1_13  GCA_002289875.1  F00691_06
44   PCZA01000001.1_92  GCA_002553925.1  F00691_06
45   PCZH01000004.1_46  GCA_002554075.1  F00691_06
46  PECX01000001.1_247  GCA_002738245.1  F00691_06
47   PKGN01000021.1_47  GCA_002848245.1  F00691_06
48  QFAS01000010.1_270  GCA_003129685.1  F00691_06
49      CP029616.1_751  GCA_003316955.1  F00691_06
50  QSTB01000006.1_106  GCA_003438595.1  F00691_06
51  QSLH01000006.1_120  GCA_003470145.1  F00691_06
52   QRMK01000003.1_53  GCA_003472615.1  F00691_06
53      LT604074.1_698  GCA_900094615.1  F00691_06
GCA_000143435.1
GCA_002079655.1
GCA_001011095.1
GCA_001063855.1
GCA_002079335.1
GCA_002079365.1
GCA_002079435.1
GCA_002079525.1
GCA_002079645.1
GCA_002079715.1
GCA_002079765.1
GCA_003438595.1
GCA_003472615.1
                 gene           genome orthogroup
54      CP002035.1_35  GCA_000143435.1  F00239_09
55      CP002035.1_36  GCA_000143435.1  F00239_09
56  NBEP01000004.1_12  GCA_002079655.1  F00239_09
57      CP011405.1_27  GCA_001011095.1  F00239_09
58   JVAF01000004.1_1  GCA_001063855.1  F00239_09
59   NBDX01000030.1_3  GCA_002079335.1  F00239_09
60   NBDZ01000027.1_3  GCA_002079365.1  F00239_09
61   NBED01000040.1_5  GCA_002079435.1  F00239_09
62   NBEJ01000023.1_3  GCA_002079525.1  F00239_09
63   NBEQ01000045.1_3  GCA_002079645.1  F00239_09
64   NBET01000035.1_3  GCA_002079715.1  F00239_09
65   NBEX01000086.1_3  GCA_002079765.1  F00239_09
66   QSTB01000024.1_4  GCA_003438595.1  F00239_09
67   QRMK01000022.1_6  GCA_003472615.1  F00239_09
GCA_000143435.1
GCA_000179475.1
GCA_002079655.1
GCA_003513805.1
GCA_000215465.2
GCA_000217735.2
GCA_000260335.1
GCA_000529385.1
GCA_000758365.1
GCA_001011095.1
GCA_001063855.1
GCA_001067265.1
GCA_001435955.1
GCA_001723525.1
GCA_002079325.1
GCA_002079335.1
GCA_002079365.1
GCA_002079425.1
GCA_002079435.1
GCA_002079465.1
GCA_002079525.1
GCA_002079595.1
GCA_002079645.1
GCA_002079705.1
GCA_002079715.1
GCA_002079745.1
GCA_002079765.1
GCA_002079785.1
GCA_002079795.1
GCA_002079905.1
GCA_002079925.1
GCA_002135095.1
GCA_002159345.1
GCA_002160855.1
GCA_002161265.1
GCA_002162055.1
GCA_002250405.1
GCA_002289615.1
GCA_002289685.1
GCA_002289725.1
GCA_002289745.1
GCA_002289795.1
GCA_002289875.1
GCA_002553925.1
GCA_002554075.1
GCA_002738245.1
GCA_002848245.1
GCA_003129685.1
GCA_003438595.1
GCA_003470145.1
GCA_003472615.1
GCA_900094615.1
                   gene           genome orthogroup
68       CP002037.1_184  GCA_000143435.1   F00268_1
69    AEBA01000075.1_15  GCA_000179475.1   F00268_1
70     NBEP01000087.1_2  GCA_002079655.1   F00268_1
71    DONQ01000002.1_62  GCA_003513805.1   F00268_1
72    AFMN01000003.1_37  GCA_000215465.2   F00268_1
73    AFOI01000009.1_38  GCA_000217735.2   F00268_1
74    AICL01000008.1_31  GCA_000260335.1   F00268_1
75   CBVR010000001.1_52  GCA_000529385.1   F00268_1
76       CP007647.1_139  GCA_000758365.1   F00268_1
77        CP011404.1_79  GCA_001011095.1   F00268_1
78     JVAF01000109.1_6  GCA_001063855.1   F00268_1
79    JUTI01000054.1_17  GCA_001067265.1   F00268_1
80    AYYT01000015.1_29  GCA_001435955.1   F00268_1
81        CP017108.1_52  GCA_001723525.1   F00268_1
82    NBEA01000028.1_35  GCA_002079325.1   F00268_1
83    NBDX01000033.1_42  GCA_002079335.1   F00268_1
84   NBDZ01000035.1_105  GCA_002079365.1   F00268_1
85    NBEF01000034.1_90  GCA_002079425.1   F00268_1
86    NBED01000042.1_55  GCA_002079435.1   F00268_1
87    NBEG01000026.1_11  GCA_002079465.1   F00268_1
88     NBEJ01000028.1_9  GCA_002079525.1   F00268_1
89   NBEN01000014.1_187  GCA_002079595.1   F00268_1
90   NBEQ01000054.1_154  GCA_002079645.1   F00268_1
91    NBES01000046.1_23  GCA_002079705.1   F00268_1
92    NBET01000043.1_76  GCA_002079715.1   F00268_1
93   NBEU01000021.1_107  GCA_002079745.1   F00268_1
94   NBEX01000093.1_185  GCA_002079765.1   F00268_1
95     NBEV01000061.1_5  GCA_002079785.1   F00268_1
96     NBEB01000099.1_8  GCA_002079795.1   F00268_1
97     MSCR01000035.1_9  GCA_002079905.1   F00268_1
98   NBDY01000017.1_107  GCA_002079925.1   F00268_1
99    LXZG01000089.1_12  GCA_002135095.1   F00268_1
100   NFHV01000010.1_52  GCA_002159345.1   F00268_1
101   NFLK01000010.1_27  GCA_002160855.1   F00268_1
102   NFHF01000007.1_55  GCA_002161265.1   F00268_1
103       CP020859.1_71  GCA_002162055.1   F00268_1
104   NDYW01000017.1_10  GCA_002250405.1   F00268_1
105    LXZS01000055.1_6  GCA_002289615.1   F00268_1
106   LXZL01000047.1_71  GCA_002289685.1   F00268_1
107   LXZJ01000041.1_26  GCA_002289725.1   F00268_1
108   LXZH01000027.1_18  GCA_002289745.1   F00268_1
109   LXZD01000022.1_34  GCA_002289795.1   F00268_1
110   LXZA01000006.1_12  GCA_002289875.1   F00268_1
111    PCZA01000054.1_9  GCA_002553925.1   F00268_1
112   PCZH01000024.1_34  GCA_002554075.1   F00268_1
113   PECX01000002.1_80  GCA_002738245.1   F00268_1
114   PKGN01000045.1_10  GCA_002848245.1   F00268_1
115  QFAS01000008.1_116  GCA_003129685.1   F00268_1
116   QSTB01000004.1_26  GCA_003438595.1   F00268_1
117   QSLH01000009.1_83  GCA_003470145.1   F00268_1
118   QRMK01000024.1_24  GCA_003472615.1   F00268_1
119       LT604075.1_72  GCA_900094615.1   F00268_1

In [8]:
order = pangenome["gene"].str.split("_", n = 1, expand = True)
order[1] = pd.to_numeric(order[1])
order.columns = ["contig", "order"]
order

             contig  order
0        CP002034.1   1719
1    AEBA01000134.1     40
2    NBEP01000018.1     44
3    DONQ01000011.1     12
4    AFMN01000001.1    591
..              ...    ...
115  QFAS01000008.1    116
116  QSTB01000004.1     26
117  QSLH01000009.1     83
118  QRMK01000024.1     24
119      LT604075.1     72

[120 rows x 2 columns]

In [9]:
full_order = order.merge(pangenome, left_index= True, right_index= True)
full_order.sort_values(by=['contig','order'])

             contig  order                gene           genome orthogroup
69   AEBA01000075.1     15   AEBA01000075.1_15  GCA_000179475.1   F00268_1
1    AEBA01000134.1     40   AEBA01000134.1_40  GCA_000179475.1  F00691_06
4    AFMN01000001.1    591  AFMN01000001.1_591  GCA_000215465.2  F00691_06
72   AFMN01000003.1     37   AFMN01000003.1_37  GCA_000215465.2   F00268_1
5    AFOI01000002.1    167  AFOI01000002.1_167  GCA_000217735.2  F00691_06
..              ...    ...                 ...              ...        ...
51   QSLH01000006.1    120  QSLH01000006.1_120  GCA_003470145.1  F00691_06
117  QSLH01000009.1     83   QSLH01000009.1_83  GCA_003470145.1   F00268_1
116  QSTB01000004.1     26   QSTB01000004.1_26  GCA_003438595.1   F00268_1
50   QSTB01000006.1    106  QSTB01000006.1_106  GCA_003438595.1  F00691_06
66   QSTB01000024.1      4    QSTB01000024.1_4  GCA_003438595.1  F00239_09

[120 rows x 5 columns]

In [13]:
full_order.loc[full_order.genome=="GCA_002079745.1"]

            contig  order                gene           genome orthogroup
26  NBEU01000019.1     14   NBEU01000019.1_14  GCA_002079745.1  F00691_06
93  NBEU01000021.1    107  NBEU01000021.1_107  GCA_002079745.1   F00268_1

In [12]:
gffutils.create_db(gff, "GCA_000006785.2_db")

OperationalError: table features already exists

In [13]:
db = gffutils.FeatureDB(dbfn="GCA_000006785.2_db")

In [14]:
df=pd.DataFrame(columns = ['contig', 'ID', 'start', 'end', 'strand'])
df

Empty DataFrame
Columns: [contig, ID, start, end, strand]
Index: []

In [15]:
query = db.execute("select seqid,start,end,strand,attributes from features where featuretype = 'CDS'")
result = query.fetchall()

for each in result:
    #print(each['end'])
    #df=df.append({'ID':1, 'contig':2, 'end':3, 'start':4}, ignore_index=True)
    df=df.append({'ID':json.loads(each['attributes'])['ID'][0], 'contig':each['seqid'], 'end':each['end'], 'start':each['start'], 'strand':each['strand']}, ignore_index=True)
    #print(each['seqid'])
    #print(each['start'])
    #print(each['end'])
    #print(json.loads(each['attributes'])['ID'][0])

In [16]:
df[(df.start>=1773339) & (df.end<=1786888)]

          contig      ID    start      end strand
1697  AE004092.2  1_1698  1773449  1774594      -
1698  AE004092.2  1_1699  1775853  1776620      -
1699  AE004092.2  1_1700  1776774  1776980      +
1700  AE004092.2  1_1701  1777014  1777781      +
1701  AE004092.2  1_1702  1777791  1778414      +
1702  AE004092.2  1_1703  1778414  1778683      +
1703  AE004092.2  1_1704  1778939  1779280      +
1704  AE004092.2  1_1705  1779267  1779488      +
1705  AE004092.2  1_1706  1779491  1779682      +
1706  AE004092.2  1_1707  1779694  1780023      +
1707  AE004092.2  1_1708  1780026  1780298      +
1708  AE004092.2  1_1709  1780299  1781156      +
1709  AE004092.2  1_1710  1781125  1782813      +
1710  AE004092.2  1_1711  1783100  1783273      +
1711  AE004092.2  1_1712  1783279  1783452      +
1712  AE004092.2  1_1713  1783454  1783963      +
1713  AE004092.2  1_1714  1784037  1784525      +
1714  AE004092.2  1_1715  1784929  1785291      +
1715  AE004092.2  1_1716  1785266  1785649      +
1716  AE004092.2  1_1717  1785850  1786398      +

### species tree

In [1]:
genome1 = "GCA_000006785.2"

In [ ]:
!rm GCA_000006785.2_db